<?php
/**
 * Copyright © Ronangr1, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/**
 * @var \Magento\Backend\Block\Template $block
 * @var \Ronangr1\FlashMessages\ViewModel\Flash $viewModel
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$viewModel = $block->getData('view_model');
$flash = $viewModel->getFlash();
?>

<?php if ($flash): ?>
    <script>
        require(['flasher'], function (flasher) {
            const message = <?= json_encode($escaper->escapeHtml($flash['message'], ['a'])) ?>;
            const methods = {
                success: 'success',
                error: 'error',
                warning: 'warning',
                info: 'info'
            };
            const method = <?= json_encode($flash['type']) ?>;
            flasher[methods[method]](message);
        })
    </script>
    <?php endif; ?>
