<?php
/**
 * Copyright © Ronangr1, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/**
 * @var \Magento\Backend\Block\Template $block
 * @var \Ronangr1\FlashMessages\ViewModel\Flash $viewModel
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$viewModel = $block->getData('view_model');
$flash = $viewModel->getFlash();
?>

<?php if ($flash): ?>
    <?php
    $message = json_encode($flash['message']);
    $type = json_encode($flash['type']);
    $scriptString = <<<script
    require(['flasher'], function (flasher) {
        const message = JSON.parse('{$message}');
        const type = JSON.parse('{$type}');
        const methods = {
            'success': 'success',
            'error': 'error',
            'warning': 'warning',
            'info': 'info'
        };
        flasher[methods[type]](message);
    })
script;
    ?>
    <?=
    /* @noEscape */
    $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
